### ISSUE TITLE
Add Parliamentary election form of nomination and auth pdf template

### ISSUE THREAD

**Issue by YujithIsura** [ECLK/Nomination#141]
Currently there is no option to download Parliamentary election form of nomination and auth for nominations
**Description**
We have a pdf generation service for pdf generation which you can find using following link
 https://github.com/ECLK/pdf-service
With The PDF Generator API we can easily create and manage different document templates with an easy-to-use browser based document editor. And, you can use simple HTTP API calls to merge the templates with data to generate PDF.

**Solution**
- Create new html template for parliamentary election form of nomination and auth (find the template images down below ) 
- put the created template inside https://github.com/ECLK/pdf-service/tree/master/documents

**Location for PDF generation UI component**
1. Login to the party user account 
2. Select appropriate election on the initial screen (In case if you haven't seen any election on the list you will have to login ec-user account and create a call election then approve it on approve election module )
3. Click next 
4. Click on create nomination tab on left navigation bar 
5. Click on one of the nomination list item and Click on the button
6. Click on next button to go to second step of the wizard 
7. You can see the download content area 

![IMG_20200129_160007](https://user-images.githubusercontent.com/42527969/73425050-7789f600-4356-11ea-9679-db518e83d817.jpg)

![IMG_20200129_160025](https://user-images.githubusercontent.com/42527969/73425064-81135e00-4356-11ea-94b2-37c7f160c53a.jpg)

![IMG_20200129_160040](https://user-images.githubusercontent.com/42527969/73425079-8bcdf300-4356-11ea-99fa-b0c8cd94998c.jpg)

![IMG_20200129_160057](https://user-images.githubusercontent.com/42527969/73425106-9e482c80-4356-11ea-8eee-2d700f6ed559.jpg)

**Comment by YujithIsura** [comment]
worst case estimates to complete this issue is 3 Days

**Comment by hsvikum** [comment]
Will be completing this within this week.

**Comment by hsvikum** [comment]
Will be able to complete this within this week

**Comment by YujithIsura** [comment]
Thank you
