### ISSUE TITLE
Module not found: Can't resolve 'react-jss/lib/JssProvider

### ISSUE THREAD

**Issue by yasirunilan** [ECLK/Nomination#175]
**Describe the bug**
When running the command "npm start" it gives the following error "Module not found: Can't resolve 'react-jss/lib/JssProvider"

**To Reproduce**
1. run npm install 
2. run npm start

**Expected behavior**
ideally, any issue should not occur.

**Additional context**
This is the known issue with latest material-ui .
https://github.com/mui-org/material-ui/issues/13146

If You already npm install react-jss, You will probably get v10 of the package. To correct it, just do the following:

1. open package.json
2. and find the "react-jss" dependency and set it to ^8.0.0 instead of ^10.0.0
3. remove react-jss entry from package.LOCK.json (from the .lock file!!)
4. run npm install and hope for the best :)

**Comment by YujithIsura** [comment]
Thanks yasiru for pointing this out, i have added a pr to fix this issue
