### ISSUE TITLE
Download component for nomination security deposit supporting documents

### ISSUE THREAD

**Issue by YujithIsura** [ECLK/Nomination#180]
Currently there is no any option to view or download attached payslip on nomination security deposit section

**solution**
Implement a download component for attached payslip alongside with the attach button for  nomination security deposit  payslip

**Comment by YujithIsura** [comment]
worst case estimates to complete this issue is 1 Day

**Comment by yasirunilan** [comment]
I have directly pushed the code to the master branch without a pr.
