### ISSUE TITLE
Rejected election templates are not displaying

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#219]
Rejected election templates are not displaying under rejected elections tab
![rejected election not showing](https://user-images.githubusercontent.com/56621237/75248847-f7db3400-57fa-11ea-83fc-fd5fa955a24f.JPG)

**Comment by YujithIsura** [comment]
Hi Chathurika,
We did a release for that nomination form few hours ago. We did a db update
as well. That might be the reason. Really sorry for the inconvenience.
If you don’t mind can check this again
Thanks
Yujith
