### ISSUE TITLE
No menu options are displaying on home page after rejection 

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#221]
1. Reject created election
2. Navigate to home page
![Main Screen after rejection](https://user-images.githubusercontent.com/56621237/75249083-83ed5b80-57fb-11ea-9f97-b705776c89c0.JPG)

**Comment by YujithIsura** [comment]
this happens when the session got expired. can you check that again

**Comment by YujithIsura** [comment]
Already fixed
