### ISSUE TITLE
Created user shown as ‘Admin’, not the ‘ec-nom-ce’ (one logged in)

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#226]
Created user shown as ‘Admin’, not the ‘ec-nom-ce’ (one logged in)

![issue_16](https://user-images.githubusercontent.com/56621237/75515681-a1e7d580-5a20-11ea-9dbb-0508412af7eb.png)

**Comment by YujithIsura** [comment]
This issue covers from another pending issue, so I'm closing this
