### ISSUE TITLE
Filter table option is having a blank value and ‘Object Object’ values on its dropdown.

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#227]
Filter table option is having a blank value and ‘Object Object’ values on its dropdown.

![issue_15A](https://user-images.githubusercontent.com/56621237/75515788-e6737100-5a20-11ea-8827-91303f331c20.png)
![issue_15B](https://user-images.githubusercontent.com/56621237/75515791-e83d3480-5a20-11ea-9dd2-df9ba3f3fa33.png)

**Comment by YujithIsura** [comment]
This fixed with issue no #231
