### ISSUE TITLE
Sort from Party column (applicable for any other column as well) and check/uncheck any box. Sorting disappears and party’s starts with N come to top.

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#228]
Sort from Party column (applicable for any other column as well) and check/uncheck any box. Sorting disappears and the party’s starts with N come to the top.

![issue_14](https://user-images.githubusercontent.com/56621237/75515922-3d794600-5a21-11ea-9c7f-0509a1d3e1dc.png)
![issue_14B](https://user-images.githubusercontent.com/56621237/75515924-3eaa7300-5a21-11ea-8e56-00697c00e6d2.png)

**Comment by YujithIsura** [comment]
Sorting feature disabled for this section due to unnecessary usage
