### ISSUE TITLE
SUGGESTION: Can a waiting/loading animation be put on for anything that we have to wait – Download for example – once clicked page pretty much get stuck until it gets ready on background.

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#233]
SUGGESTION: Can a waiting/loading animation be put on for anything that we have to wait – Download for example – once clicked page pretty much get stuck until it gets ready on the background.

![issue_7](https://user-images.githubusercontent.com/56621237/75517607-1d4b8600-5a25-11ea-9ef1-cc0f64615b37.png)

Places need to put loading components (Progress Spinners)

- [ ] Click upon call election first step next button
- [ ] Click election approval list item edit/view buttons
- [ ] Click upon nomination security deposit download pdf button

**Comment by YujithIsura** [comment]
Will do this, thank you
