### ISSUE TITLE
After couple of wrong date entries (& next button clicks), left navigation bar gets disappeared. This happens for some other random actions as well.

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#234]
After couple of wrong date entries (& next button clicks), left navigation bar gets disappeared. This happens for some other random actions as well.

![issue_6](https://user-images.githubusercontent.com/56621237/75518541-2ccbce80-5a27-11ea-80df-482449d347c9.png)

**Comment by YujithIsura** [comment]
This happens when your session got expired. after 15 min of inactivity might expire your session.
will check anyway

**Comment by YujithIsura** [comment]
already fixed
