### ISSUE TITLE
complete the form – then it will not get saved. And shown below

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#235]
After couple of wrong date entries (& next button clicks), left navigation bar gets disappeared. This happens for some other random actions as well.

Once this happens and we complete the form – then it will not get saved. And shown below.

![issue_6](https://user-images.githubusercontent.com/56621237/75519024-4c172b80-5a28-11ea-91f8-92b0615c1a59.png)
![issue_6B](https://user-images.githubusercontent.com/56621237/75519025-4d485880-5a28-11ea-989a-aeeac10265ac.png)

**Comment by YujithIsura** [comment]
This happened becouse of session time expire issue on staging env, This issue is already fixed
