### ISSUE TITLE
Nomination Security Deposit: Field labels are highlighted in red color

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#242]
Nomination Security Deposit: Field labels are highlighted in red color
![Text field](https://user-images.githubusercontent.com/56621237/75612480-c1c6e880-5b49-11ea-9e25-ff98db98fddd.JPG)

**Comment by YujithIsura** [comment]
Hi @Chathurikaweerasinghe this is the normal behavior of react material ui error textfield 
so im closing this issue
