### ISSUE TITLE
SUGGESTION: Move cancels out from back / next button.

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#245]
SUGGESTION: Move cancels out from back / next button.

![issue_20A](https://user-images.githubusercontent.com/56621237/75613568-36535480-5b55-11ea-99d1-07d72247e9d1.png)
![issue_20B](https://user-images.githubusercontent.com/56621237/75613569-37848180-5b55-11ea-96ed-27202d8c0e5b.png)

**Comment by nshamit** [comment]
The react component comes w/ a preset order (industry standard) so we will keep it this way.
