### ISSUE TITLE
When all available options were selected/ticked and multiple + were added, Election templates created are not getting saved. -	Afterwards Logged in user (ec-nom-ce) cannot see his or already approved/rejected/pending templates. But can see all call election created/rejected/pending once.

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#249]
When all available options were selected/ticked and multiple + were added, Election templates created are not getting saved.
-	Afterward Logged in user (ec-nom-ce) cannot see his or already approved/rejected/pending templates. But can see all call elections created/rejected/pending once.

![issue_23](https://user-images.githubusercontent.com/56621237/75613667-63543700-5b56-11ea-8e2c-e584fd5222ff.png)

**Comment by Chathurikaweerasinghe** [comment]
-	When try to create a new template – no checkbox are enabling to select. As well as noting works on-call election section. Could have been triggered from the special characters &/or minus values entered.


![issue_23B](https://user-images.githubusercontent.com/56621237/75613686-95fe2f80-5b56-11ea-9920-a9388e6b5d0c.png)

**Comment by YujithIsura** [comment]
This happened because of permission issue with wso2 API manager, fixed with above pr
@Chathurikaweerasinghe thanks for finding this one
