### ISSUE TITLE
Cannot proceed nomination approval when user selects election and party. User gets no options to continue further

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#251]
Cannot proceed nomination approval when user selects election and party. User gets no options to continue further

![Nomination_approval](https://user-images.githubusercontent.com/56621237/75613846-1cffd780-5b58-11ea-9609-b4c688af01bb.JPG)

**Comment by YujithIsura** [comment]
This means the selected party or election doesn't have any pending nominations. we will implement a message to the user if there is no any pending nominations
