### ISSUE TITLE
Created election template get disappeared,once user updated it

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/Nomination#304]
login as ec-nom-ce
Create Election Template
Created template displays under Pending elections
Select created election and click on update (User does not need to update. Just go update flow and click on the update button at final)
System displays message saying "Something went wrong" and updated template get disappeared

![Update_election_template](https://user-images.githubusercontent.com/56621237/77293877-3d5f2400-6d09-11ea-80c0-fee6d32cdee7.JPG)

**Comment by YujithIsura** [comment]
This issue occurred due to insufficient permission for this user roll, fixed by setting the right scope for appropriate and point from wso2 API Manager
